import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { getAuth } from 'firebase/auth'
import firebaseApp from '../firebase'
import Link from "next/link";
import PostsList from "../components/PostsList";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props) {

  // const onSignOutClicked = () => {
  //   const auth = getAuth(firebaseApp);
  //   auth.signOut()
  // }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          {/* {props.user && <button onClick={onSignOutClicked}>Sign Out</button>}
          {!props.user && <Link href="/login">Login</Link>} */}
          <p>
            {props.user && JSON.stringify(props.user, null, 2)}
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p>
        </div>

        <PostsList />
      </main>
    </>
  );
}
